[meta]
  title = "Deepgram Node.js Starter"
  description = "Basic demo for using Deepgram with Node.js"
  author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
  useCase = "prerecorded"
  language = "javascript"
  framework = "node"

[build]
  command = "npm install"

[config]
  sample = "config.json.example"
  output = "config.json"

[post-build]
  message = "Run `npm start` to get up and running."
